Repository HOLOS-International-Solutions/HOLOS-Intl, pull requests merged in 2025-02, with the labels that each got.

#13 Farm Creation, Selection & Import Views
  H.GUI.Avalonia/H.Avalonia/App.axaml.cs
  H.GUI.Avalonia/H.Avalonia/Assets/Images/Icons/search-icon.png
  H.GUI.Avalonia/H.Avalonia/H.Avalonia.csproj
  H.GUI.Avalonia/H.Avalonia/ViewModels/FarmCreationViews/FarmCreationViewModel.cs
  H.GUI.Avalonia/H.Avalonia/ViewModels/FarmCreationViews/FarmOpenExistingViewModel.cs
  H.GUI.Avalonia/H.Avalonia/ViewModels/FarmCreationViews/FarmOptionsViewModel.cs
  H.GUI.Avalonia/H.Avalonia/ViewModels/SupportingViews/Disclaimer/DisclaimerViewModel.cs
  H.GUI.Avalonia/H.Avalonia/Views/FarmCreationViews/FarmCreationView.axaml
  H.GUI.Avalonia/H.Avalonia/Views/FarmCreationViews/FarmCreationView.axaml.cs
  H.GUI.Avalonia/H.Avalonia/Views/FarmCreationViews/FarmOpenExistingView.axaml
  H.GUI.Avalonia/H.Avalonia/Views/FarmCreationViews/FarmOpenExistingView.axaml.cs
  H.GUI.Avalonia/H.Avalonia/Views/FarmCreationViews/FarmOptionsView.axaml
  H.GUI.Avalonia/H.Avalonia/Views/FarmCreationViews/FarmOptionsView.axaml.cs
Labels: Feature Development

#25 Created default constructors for FarmCreationViews.
  H.GUI.Avalonia/H.Avalonia/Views/FarmCreationViews/FarmCreationView.axaml.cs
  H.GUI.Avalonia/H.Avalonia/Views/FarmCreationViews/FarmOpenExistingView.axaml.cs
  H.GUI.Avalonia/H.Avalonia/Views/FarmCreationViews/FarmOptionsView.axaml.cs
Labels: bug

#27 Moved strings from FarmCreationViews to Resources
  H.Core/Properties/Resources.Designer.cs
  H.Core/Properties/Resources.resx
  H.GUI.Avalonia/H.Avalonia/Views/FarmCreationViews/FarmCreationView.axaml
  H.GUI.Avalonia/H.Avalonia/Views/FarmCreationViews/FarmOpenExistingView.axaml
  H.GUI.Avalonia/H.Avalonia/Views/FarmCreationViews/FarmOptionsView.axaml
Labels: documentation

#28 Modified OpenExistingView to bind datagrid with getAllFarms
  H.Core/Properties/Resources.Designer.cs
  H.Core/Properties/Resources.resx
  H.GUI.Avalonia/H.Avalonia/ViewModels/FarmCreationViews/FarmOpenExistingViewModel.cs
  H.GUI.Avalonia/H.Avalonia/Views/FarmCreationViews/FarmCreationView.axaml
  H.GUI.Avalonia/H.Avalonia/Views/FarmCreationViews/FarmOpenExistingView.axaml
  H.GUI.Avalonia/H.Avalonia/Views/FarmCreationViews/FarmOptionsView.axaml
Labels: Feature Development

#29 Added Validation to the CreateFarmViewModel
  H.GUI.Avalonia/H.Avalonia/ViewModels/FarmCreationViews/FarmCreationViewModel.cs
  H.GUI.Avalonia/H.Avalonia/ViewModels/ViewModelBase.cs
  H.GUI.Avalonia/H.Avalonia/Views/FarmCreationViews/FarmCreationView.axaml
Labels: Feature Development

#30 Implemented Other Animals Views + View Models
  H.GUI.Avalonia/H.Avalonia.Test/ViewModels/ComponentViews/OtherAnimals/BisonComponentViewModelTests.cs
  H.GUI.Avalonia/H.Avalonia.Test/ViewModels/ComponentViews/OtherAnimals/DeerComponentViewModelTests.cs
  H.GUI.Avalonia/H.Avalonia.Test/ViewModels/ComponentViews/OtherAnimals/GoatsComponentViewModelTests.cs
  H.GUI.Avalonia/H.Avalonia.Test/ViewModels/ComponentViews/OtherAnimals/HorsesComponentViewModelTests.cs
  H.GUI.Avalonia/H.Avalonia.Test/ViewModels/ComponentViews/OtherAnimals/LlamaComponentViewModelTests.cs
  H.GUI.Avalonia/H.Avalonia.Test/ViewModels/ComponentViews/OtherAnimals/MulesComponentViewModelTests.cs
  H.GUI.Avalonia/H.Avalonia.Test/ViewModels/ComponentViews/OtherAnimals/OtherAnimalsViewModelBaseTests.cs
  H.GUI.Avalonia/H.Avalonia/ViewModels/ComponentViews/OtherAnimals/BisonComponentViewModel.cs
  H.GUI.Avalonia/H.Avalonia/ViewModels/ComponentViews/OtherAnimals/BisonComponentViewModelDesign.cs
  H.GUI.Avalonia/H.Avalonia/ViewModels/ComponentViews/OtherAnimals/DeerComponentViewModel.cs
  H.GUI.Avalonia/H.Avalonia/ViewModels/ComponentViews/OtherAnimals/DeerComponentViewModelDesign.cs
  H.GUI.Avalonia/H.Avalonia/ViewModels/ComponentViews/OtherAnimals/GoatsComponentViewModel.cs
  H.GUI.Avalonia/H.Avalonia/ViewModels/ComponentViews/OtherAnimals/GoatsComponentViewModelDesign.cs
  H.GUI.Avalonia/H.Avalonia/ViewModels/ComponentViews/OtherAnimals/HorsesComponentViewModel.cs
  H.GUI.Avalonia/H.Avalonia/ViewModels/ComponentViews/OtherAnimals/HorsesComponentViewModelDesign.cs
  H.GUI.Avalonia/H.Avalonia/ViewModels/ComponentViews/OtherAnimals/LlamaComponentViewModel.cs
  H.GUI.Avalonia/H.Avalonia/ViewModels/ComponentViews/OtherAnimals/LlamaComponentViewModelDesign.cs
  H.GUI.Avalonia/H.Avalonia/ViewModels/ComponentViews/OtherAnimals/MulesComponentViewModel.cs
  H.GUI.Avalonia/H.Avalonia/ViewModels/ComponentViews/OtherAnimals/MulesComponentViewModelDesign.cs
  H.GUI.Avalonia/H.Avalonia/ViewModels/ComponentViews/OtherAnimals/OtherAnimalsViewModelBase.cs
  H.GUI.Avalonia/H.Avalonia/Views/ComponentViews/OtherAnimals/BisonComponentView.axaml
  H.GUI.Avalonia/H.Avalonia/Views/ComponentViews/OtherAnimals/DeerComponentView.axaml
  H.GUI.Avalonia/H.Avalonia/Views/ComponentViews/OtherAnimals/GoatsComponentView.axaml
  H.GUI.Avalonia/H.Avalonia/Views/ComponentViews/OtherAnimals/HorsesComponentView.axaml
  H.GUI.Avalonia/H.Avalonia/Views/ComponentViews/OtherAnimals/LlamaComponentView.axaml
  H.GUI.Avalonia/H.Avalonia/Views/ComponentViews/OtherAnimals/MulesComponentView.axaml
  H.GUI.Avalonia/H.Avalonia/Views/ComponentViews/OtherAnimals/OtherAnimalsComponentsView.axaml
  H.GUI.Avalonia/H.Avalonia/Views/ComponentViews/OtherAnimals/OtherAnimalsComponentsView.axaml.cs
  H.GUI.Avalonia/H.Avalonia/Views/ComponentViews/OtherAnimals/OtherAnimalsStep1View.axaml
  H.GUI.Avalonia/H.Avalonia/Views/ComponentViews/OtherAnimals/OtherAnimalsStep1View.axaml.cs
  H.GUI.Avalonia/H.Avalonia/Views/ComponentViews/OtherAnimals/OtherAnimalsStep2View.axaml
  H.GUI.Avalonia/H.Avalonia/Views/ComponentViews/OtherAnimals/OtherAnimalsStep2View.axaml.cs
  H.GUI.Avalonia/H.Avalonia/Views/ComponentViews/OtherAnimals/OtherAnimalsStep3View.axaml
  H.GUI.Avalonia/H.Avalonia/Views/ComponentViews/OtherAnimals/OtherAnimalsStep3View.axaml.cs
Labels: Feature Development

#31 Added Resource strings for OtherAnimals Views + Facored out styles to Control Styles
  H.Core/Properties/Resources.Designer.cs
  H.Core/Properties/Resources.resx
  H.GUI.Avalonia/H.Avalonia/Styles/ControlsStyles.axaml
  H.GUI.Avalonia/H.Avalonia/ViewModels/ComponentViews/OtherAnimals/OtherAnimalsViewModelBase.cs
  H.GUI.Avalonia/H.Avalonia/Views/ComponentViews/OtherAnimals/OtherAnimalsComponentsView.axaml
  H.GUI.Avalonia/H.Avalonia/Views/ComponentViews/OtherAnimals/OtherAnimalsStep1View.axaml
  H.GUI.Avalonia/H.Avalonia/Views/ComponentViews/OtherAnimals/OtherAnimalsStep2View.axaml
  H.GUI.Avalonia/H.Avalonia/Views/ComponentViews/OtherAnimals/OtherAnimalsStep3View.axaml
Labels: documentation

#32 Update open existing farm view model and MycomponentsViewModel
  H.Core/IStorage.cs
  H.GUI.Avalonia/H.Avalonia/App.axaml.cs
  H.GUI.Avalonia/H.Avalonia/ViewModels/ComponentViews/MyComponentsViewModel.cs
  H.GUI.Avalonia/H.Avalonia/ViewModels/FarmCreationViews/FarmOpenExistingViewModel.cs
  H.GUI.Avalonia/H.Avalonia/ViewModels/ViewModelBase.cs
  H.GUI.Avalonia/H.Avalonia/Views/FarmCreationViews/FarmOpenExistingView.axaml
Labels: Feature Development

#33 Adding a View Model for ManagementPeriods (Validation Logic) + Tests
  H.Core/Properties/Resources.Designer.cs
  H.Core/Properties/Resources.fr-CA.resx
  H.Core/Properties/Resources.resx
  H.GUI.Avalonia/H.Avalonia.Test/ViewModels/ComponentViews/ManagementPeriodViewModelTests.cs
  H.GUI.Avalonia/H.Avalonia.Test/ViewModels/ComponentViews/OtherAnimals/BisonComponentViewModelTests.cs
  H.GUI.Avalonia/H.Avalonia.Test/ViewModels/ComponentViews/OtherAnimals/DeerComponentViewModelTests.cs
  H.GUI.Avalonia/H.Avalonia.Test/ViewModels/ComponentViews/OtherAnimals/GoatsComponentViewModelTests.cs
  H.GUI.Avalonia/H.Avalonia.Test/ViewModels/ComponentViews/OtherAnimals/HorsesComponentViewModelTests.cs
  H.GUI.Avalonia/H.Avalonia.Test/ViewModels/ComponentViews/OtherAnimals/LlamaComponentViewModelTests.cs
  H.GUI.Avalonia/H.Avalonia.Test/ViewModels/ComponentViews/OtherAnimals/MulesComponentViewModelTests.cs
  H.GUI.Avalonia/H.Avalonia.Test/ViewModels/ComponentViews/OtherAnimals/OtherAnimalsViewModelBaseTests.cs
  H.GUI.Avalonia/H.Avalonia/App.config
  H.GUI.Avalonia/H.Avalonia/H.Avalonia.csproj
  H.GUI.Avalonia/H.Avalonia/ViewModels/ComponentViews/ManagementPeriodViewModel.cs
  H.GUI.Avalonia/H.Avalonia/ViewModels/ComponentViews/OtherAnimals/BisonComponentViewModel.cs
  H.GUI.Avalonia/H.Avalonia/ViewModels/ComponentViews/OtherAnimals/BisonComponentViewModelDesign.cs
  H.GUI.Avalonia/H.Avalonia/ViewModels/ComponentViews/OtherAnimals/DeerComponentViewModel.cs
  H.GUI.Avalonia/H.Avalonia/ViewModels/ComponentViews/OtherAnimals/DeerComponentViewModelDesign.cs
  H.GUI.Avalonia/H.Avalonia/ViewModels/ComponentViews/OtherAnimals/GoatsComponentViewModel.cs
  H.GUI.Avalonia/H.Avalonia/ViewModels/ComponentViews/OtherAnimals/GoatsComponentViewModelDesign.cs
  H.GUI.Avalonia/H.Avalonia/ViewModels/ComponentViews/OtherAnimals/HorsesComponentViewModel.cs
  H.GUI.Avalonia/H.Avalonia/ViewModels/ComponentViews/OtherAnimals/HorsesComponentViewModelDesign.cs
  H.GUI.Avalonia/H.Avalonia/ViewModels/ComponentViews/OtherAnimals/LlamaComponentViewModel.cs
  H.GUI.Avalonia/H.Avalonia/ViewModels/ComponentViews/OtherAnimals/LlamaComponentViewModelDesign.cs
  H.GUI.Avalonia/H.Avalonia/ViewModels/ComponentViews/OtherAnimals/MulesComponentViewModel.cs
  H.GUI.Avalonia/H.Avalonia/ViewModels/ComponentViews/OtherAnimals/MulesComponentViewModelDesign.cs
  H.GUI.Avalonia/H.Avalonia/ViewModels/ComponentViews/OtherAnimals/OtherAnimalsViewModelBase.cs
  H.GUI.Avalonia/H.Avalonia/ViewModels/ViewModelBase.cs
  H.GUI.Avalonia/H.Avalonia/Views/ComponentViews/OtherAnimals/OtherAnimalsStep2View.axaml
Labels: Feature Development
